runner:
  n_epochs: -1
  total_steps: 250000
  gradient_clipping: 10.0
  gradient_accumulate_steps: 1
 
  log_step: 500

optimizer:
  lr: 1.e-5
  betas: [0.9, 0.999]
  eps: 1.e-8
  weight_decay: 0

datarc:
  num_workers: 8
  train_batch_size: 4
  max_timestep: -320
  sets: ['/home/nervjack2/libri-with-cluster/csv/libri-360-np-stage1.csv']

prune:
  total_steps: 5 # total pruning steps
  num_rows_each_step: 512  
  interval: [0, 50000, 100000, 150000, 200000]
  # interval: [1, 6, 11, 16, 21]
  warm_up: 1000
  # warm_up: 1
