task:
  _name: hubert_pretraining
  data: /mnt/data/ycevan/datasets/LibriSpeech/pseudolabel_manifest
  label_dir: /mnt/data/ycevan/datasets/LibriSpeech/labels/960h-hubert-speculte-stg2-target
  labels: ['km']
  label_rate: 50
  sample_rate: 16000
  max_sample_size: 250000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: false # must be consistent with extractor

pretrain_expert:
  datarc:
    num_workers: 6
    train_batch_size: 12
  
runner:
  n_epochs: 18
  total_steps: -1
  gradient_clipping: 10.0
  gradient_accumulate_steps: 1

  log_step: 200
  save_step: 50000
  max_keep: 5
  fp16: true

optimizer:
  lr: 0.0005
  betas: (0.9,0.98)
  eps: 1e-06
  weight_decay: 0.01

prune:
  total_steps: 20 # total pruning steps
  num_rows_each_step: 128
  interval: [0, 25000, 50000, 75000, 100000, 125000, 150000, 175000, 200000, 
              225000, 250000, 275000, 300000, 325000, 350000, 375000, 400000, 425000, 450000, 475000]
  warm_up: 5000
