runner:
  n_epochs: -1
  total_steps: 510000
  gradient_clipping: 10.0
  gradient_accumulate_steps: 1
  fp16: true
  log_step: 200

task:
  _name: audio_pretraining
  data: /mnt/data/ycevan/datasets/LibriSpeech/manifest
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

pretrain_expert:
  datarc:
    num_workers: 6
    train_batch_size: 12
  
optimizer:
  lr: 1.e-5
  betas: [0.9, 0.999]
  eps: 1.e-8
  weight_decay: 0.0

prune:
  total_steps: 20 # total pruning steps
  num_rows_each_step: 128
  interval: [0, 25000, 50000, 75000, 100000, 125000, 150000, 175000, 200000, 
              225000, 250000, 275000, 300000, 325000, 350000, 375000, 400000, 425000, 450000, 475000]
  warm_up: 1000
