runner:
  n_epochs: -1
  total_steps: 200005
  gradient_clipping: 5.0
  gradient_accumulate_steps: 1

  log_step: 50
  # Save checkpoint for every save_every_x_epochs epochs
  # save_every_x_epochs: 4
  save_steps: 10000
  fp16: true

optimizer:
  lr: 2.e-4
  betas: [0.9, 0.98]
  eps: 1.e-6
  weight_decay: 1.e-6

lr_scheduler:
  warmup_updates: 14000
  
pretrain_expert:
  datarc:
    num_workers: 8
    train_batch_size: 24
    max_timestep: -320 # Max length for audio feature (0 for no restriction, negative value to set minimum timestep)
    sets: ['/mnt/data/ycevan/datasets/melhubert/libri960-stg2-20ms.csv']
      
