model:
  _name: hubert
  label_rate: 50
  skip_masked: false
  skip_nomask: false
  mask_prob: 0.8
  extractor_mode: default
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  final_dim: 256
  encoder_layerdrop: 0.0
  dropout_input: 0.0
  dropout_features: 0.0
  dropout: 0.0
  attention_dropout: 0.0
  feature_grad_mult: 0.1
  untie_final_proj: true
  activation_dropout: 0.0